version: "3"

services:
  mawanda-pg:
    image: bitnami/postgresql
    container_name: mawanda_Database
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=mariogomes
      - POSTGRESQL_PASSWORD=1qaz2wsx
      - POSTGRESQL_DATABASE=minhasreceitas
    volumes:
      - pgdata:/data/postgres
    network_mode: host

  mawanda-redis:
    image: bitnami/redis
    container_name: mawanda-redis
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD=1qaz2wsx
    volumes:
      - pgdata:/data/redis
    network_mode: host
  
