//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeuLivroDeReceitas.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMensagensdeErro {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMensagensdeErro() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MeuLivroDeReceitas.Exceptions.ResourceMensagensdeErro", typeof(ResourceMensagensdeErro).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email informado é inválido.
        /// </summary>
        public static string Email_INVALIDO {
            get {
                return ResourceManager.GetString("Email_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este Email já está sendo usado por outro usuário.
        /// </summary>
        public static string Email_Já_Registrado {
            get {
                return ResourceManager.GetString("Email_Já_Registrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email do usuário deve ser informado.
        /// </summary>
        public static string Email_Usuario_Embranco {
            get {
                return ResourceManager.GetString("Email_Usuario_Embranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro Desconhecido.
        /// </summary>
        public static string Erro_Desconhecido {
            get {
                return ResourceManager.GetString("Erro_Desconhecido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O email e/ou senha estão incorretos.
        /// </summary>
        public static string LOGIN_INVALIDO {
            get {
                return ResourceManager.GetString("LOGIN_INVALIDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Nome do usuário deve ser informado.
        /// </summary>
        public static string NOME_Usuario_Embranco {
            get {
                return ResourceManager.GetString("NOME_Usuario_Embranco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ser informada.
        /// </summary>
        public static string SENHA_EMBRANCO {
            get {
                return ResourceManager.GetString("SENHA_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter no minimo 6 caracteres.
        /// </summary>
        public static string SENHA_INVALIDA {
            get {
                return ResourceManager.GetString("SENHA_INVALIDA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone do usuário deve ser informado.
        /// </summary>
        public static string TELEFONE_EMBRANCO {
            get {
                return ResourceManager.GetString("TELEFONE_EMBRANCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Telefone informado é Inválido.
        /// </summary>
        public static string TELEFONE_INVALIDO {
            get {
                return ResourceManager.GetString("TELEFONE_INVALIDO", resourceCulture);
            }
        }
    }
}
