name: Build and Test API

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Restore NuGet Packages
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.mariogomes333 }}
        password: ${{ secrets.dckr_pat_Uwu7AJXy7NN899MmZv2Q2mDzWjI }}

    - name: Build and Publish Docker Image
      run: |
        docker build -t mariogomes333/meulivroreceitas:${{ github.sha }} .
        docker push mariogomes333/meulivroreceitas:${{ github.sha }}
